import { useState } from 'react';
import { useTurbofanStream } from './hooks/useTurbofanStream';
import { Sidebar } from './components/Sidebar';
import { RULGauge } from './components/RULGauge';
import { SensorChart } from './components/SensorChart';
import { StatusIndicator } from './components/StatusIndicator';
import { FailureAlert } from './components/FailureAlert';
import { Activity } from 'lucide-react';

function App() {
  const { isConnected, enginesData } = useTurbofanStream('all');
  const [selectedEngineId, setSelectedEngineId] = useState<number | null>(null);

  // Auto-select first engine if none selected and data arrives
  const engineIds = Object.keys(enginesData).map(Number).sort((a, b) => a - b);
  if (selectedEngineId === null && engineIds.length > 0) {
    setSelectedEngineId(engineIds[0]);
  }

  const selectedEngine = selectedEngineId !== null ? enginesData[selectedEngineId] : null;
  const isCritical = selectedEngine?.status === 'Critical';

  return (
    <div className="flex h-screen bg-void text-gray-100 font-sans overflow-hidden">
      <Sidebar 
        enginesMap={enginesData} 
        selectedEngine={selectedEngineId} 
        onSelectEngine={setSelectedEngineId} 
      />
      
      <main className="flex-1 flex flex-col relative z-0">
        {/* Global Connection Header */}
        <header className="h-16 border-b border-panel-border bg-panel/50 flex items-center justify-between px-8 backdrop-blur-sm">
          <div className="flex items-center gap-4">
            <h2 className="text-sm font-mono text-gray-400 tracking-wide uppercase">
              Command Center
            </h2>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs font-mono text-gray-500 uppercase">
              Link Status
            </span>
            <div className={`px-3 py-1 rounded-full text-xs font-bold font-mono border ${isConnected ? 'bg-healthy/10 text-healthy border-healthy/30' : 'bg-critical/10 text-critical border-critical/30 animate-pulse'}`}>
              {isConnected ? 'ONLINE' : 'OFFLINE - RECONNECTING'}
            </div>
          </div>
        </header>

        {/* Dashboard Content */}
        <div className="flex-1 overflow-y-auto p-8">
          {selectedEngine ? (
            <div className="max-w-7xl mx-auto space-y-6">
              
              <div className="flex justify-between items-end mb-8">
                <div>
                  <h1 className="text-3xl font-bold tracking-widest text-white mb-2">ENG-{selectedEngine.unit_number.toString().padStart(3, '0')}</h1>
                  <p className="font-mono text-gray-400 text-sm">REAL-TIME TELEMETRY STREAM</p>
                </div>
              </div>

              {/* Top Row: Gauge & Status */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-1">
                  <RULGauge 
                    rul={selectedEngine.current_rul} 
                    bufferSize={selectedEngine.buffer_size} 
                  />
                </div>
                <div className="lg:col-span-2 flex flex-col justify-center">
                  <StatusIndicator status={selectedEngine.status} />
                  
                  <div className="mt-6 p-6 bg-panel rounded-2xl border border-panel-border shadow-lg">
                    <h3 className="text-sm font-semibold text-gray-400 mb-2 uppercase tracking-widest">
                      Analytics Note
                    </h3>
                    <p className="text-sm text-gray-500 leading-relaxed font-mono">
                      Predictions are generated by the ensemble LSTM neural network 
                      processing a 30-cycle sliding window of 18 normalized sensor features.
                      The model has standard RMSE of 12.4.
                    </p>
                  </div>
                </div>
              </div>

              {/* Bottom Row: Chart */}
              <div className="w-full">
                <SensorChart data={selectedEngine.history} />
              </div>

            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-gray-600">
              <Activity className="w-16 h-16 animate-pulse mb-6 opacity-20" />
              <p className="font-mono uppercase tracking-widest text-sm">Awaiting telemetry connection...</p>
            </div>
          )}
        </div>
      </main>

      <FailureAlert 
        isVisible={isCritical} 
        rul={selectedEngine?.current_rul || null} 
      />
    </div>
  );
}

export default App;
